# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d02cf8aa9f105bdb2e1e657b3904baf867827b7b758442c89ff6d9585cc99992e29ec8c2702e990a6f47c06380132b5c599734d4204c56bd2c9a580f09244e

test:
  secret_key_base: 4030f2d9d911a35aec08b4cb793c67004fb96e5fc88933ee47185b389a7cb7fceac5aafb51168bbfd125d5cbc15578860ac8224c2c1b0b65bff805267d211a99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
